trigger: none  # Disable direct triggers; rely solely on capacity pipeline trigger

resources:
  pipelines:
    - pipeline: capacityPipeline
      source: capacity-pipeline          # Name of the capacity pipeline in Azure DevOps
      trigger:
        branches:
          include:
            - main                       # Trigger this pipeline when capacity-pipeline runs on main

parameters:
  - name: terraform_action
    displayName: Terraform Action to perform
    type: string
    default: 'apply'
    values:
      - 'apply'
      - 'destroy'

lockBehavior: sequential

extends:
  template: ../temp-pipelines/cd-template.yaml
  parameters:
    terraform_action: ${{ parameters.terraform_action }}
    root_module_folder_relative_path: .
    variable_group: 'vars-group-workspace'

    # Add any additional parameters or overrides as needed


