trigger: none 


resources:
  pipelines:
    - pipeline: workspace  # Name of the first pipeline
      source: workspace-pipeline.yaml  # The exact name of the first pipeline in Azure DevOps
      trigger:
        branches:
          - main  # Adjust if needed (or remove if triggering on all branches)


parameters:
  - name: terraform_action
    displayName: Terraform Action to perform
    type: string
    default: 'apply'
    values:
      - 'apply'
      - 'destroy'

lockBehavior: sequential

extends:
  template: ../temp-pipelines/cd-template.yaml
  parameters:
    terraform_action: ${{ parameters.terraform_action }}
    root_module_folder_relative_path: $(Build.SourcesDirectory)/module/workspace
    # variable_group: 'vars-group-workspace'

    # Add any additional parameters or overrides as needed
